### ISSUE TITLE
Hello project with GCC

### ISSUE THREAD

**Issue by escherstair** [Open-CMSIS-Pack/csolution-examples#6]
In the [README.md](https://github.com/Open-CMSIS-Pack/csolution-examples/tree/main/Hello#readme) for  Hello project I read that Keil MDK 5.37 is a prerequisite, but then there is a note saying

> Note: later versions will also compiler with GCC.

When this will be available?

**Comment by JonatanAntoni** [comment]
Hi @escherstair,

Actually, the examples here should build for all toolchains supported by CMSIS and CMSIS-Toolbox. We could add more compilers to the GitHub workflow to be confident.
